export interface City {
  slug: string;
  name: string;
  state: string;
  county?: string;
  neighborhoods: string[];
  zipCodes?: string[];
  localRoofingNotes: string[];
  featuredServices: string[];
  nearbyCity: string[];
  description: string;
}

export const cities: City[] = [
  {
    slug: "phoenix-az",
    name: "Phoenix",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Phoenix", "Arcadia", "Ahwatukee", "North Phoenix", "Laveen", "South Mountain area", "Camelback East"],
    localRoofingNotes: [
      "Extreme UV exposure degrades asphalt shingles faster than national averages",
      "Monsoon season (June–September) brings heavy wind and rain requiring secure flashing",
      "Flat roofs common on commercial and mid-century residential properties",
      "Urban heat island effect increases thermal cycling stress on roofing materials",
      "Many HOA communities require specific tile colors and materials",
    ],
    featuredServices: ["tile-roofing", "roof-repair", "flat-roofing", "commercial-roofing"],
    nearbyCity: ["scottsdale-az", "tempe-az", "glendale-az", "mesa-az"],
    description: "As the largest city in Arizona, Phoenix presents unique roofing challenges — from intense UV exposure to powerful monsoon storms. XRP Roofing provides complete residential and commercial roofing solutions throughout the entire Phoenix metro.",
  },
  {
    slug: "scottsdale-az",
    name: "Scottsdale",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Old Town Scottsdale", "North Scottsdale", "McCormick Ranch", "Gainey Ranch", "DC Ranch", "Troon area", "South Scottsdale"],
    localRoofingNotes: [
      "Upscale communities frequently require tile roofing per HOA rules",
      "High-value homes demand premium materials and meticulous craftsmanship",
      "North Scottsdale luxury estates often feature Spanish tile or clay tile",
      "HOA architectural review boards are active — permits and color matching critical",
      "Desert landscape proximity increases debris and windblown particulate concerns",
    ],
    featuredServices: ["tile-roofing", "roof-replacement", "new-roof-installation", "storm-damage-roofing"],
    nearbyCity: ["phoenix-az", "mesa-az", "fountain-hills-az", "paradise-valley-az"],
    description: "Scottsdale's luxury residential market demands the highest standard of roofing craftsmanship. From premium tile installations in North Scottsdale's master-planned communities to fast storm damage response in Old Town, XRP Roofing delivers.",
  },
  {
    slug: "mesa-az",
    name: "Mesa",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Mesa", "Red Mountain area", "Eastmark", "Las Sendas", "Dobson Ranch", "Fiesta District", "West Mesa"],
    localRoofingNotes: [
      "Mix of older mid-century homes and newer master-planned communities",
      "Older flat-roofed homes in central Mesa are candidates for coatings or re-roof",
      "Rapid growth in east Mesa introduces new construction roofing demand",
      "Tile and shingle both popular — depends heavily on subdivision age and HOA",
      "Monsoon wind damage common in exposed eastern areas",
    ],
    featuredServices: ["shingle-roofing", "tile-roofing", "roof-repair", "roof-replacement"],
    nearbyCity: ["phoenix-az", "scottsdale-az", "chandler-az", "gilbert-az"],
    description: "Mesa is one of Arizona's most diverse roofing markets, spanning 1950s flat-roofed homes to sprawling new subdivisions. XRP Roofing handles everything from emergency repairs in central Mesa to full tile replacements in master-planned communities.",
  },
  {
    slug: "chandler-az",
    name: "Chandler",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Chandler", "Sun Lakes area", "Ocotillo", "Fulton Ranch", "Pecos area", "Chandler Heights", "Cooper Commons"],
    localRoofingNotes: [
      "Rapidly growing tech corridor brings new commercial roofing demand",
      "Mature neighborhoods in west Chandler see frequent repair and re-roof needs",
      "HOA communities dominant — material and color compliance critical",
      "Tile roofing predominates in higher-value subdivisions",
      "Flat commercial roofs common near Intel and other tech campuses",
    ],
    featuredServices: ["tile-roofing", "commercial-roofing", "roof-replacement", "tpo-roofing"],
    nearbyCity: ["mesa-az", "gilbert-az", "tempe-az", "queen-creek-az"],
    description: "Chandler's booming tech economy and established suburban neighborhoods create consistent demand for quality roofing. XRP Roofing serves both the residential communities and commercial corridors that make Chandler one of Arizona's fastest growing cities.",
  },
  {
    slug: "gilbert-az",
    name: "Gilbert",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Gilbert Heritage District", "Val Vista Lakes", "Power Ranch", "Trilogy at Power Ranch", "Greenfield Lakes", "Morrison Ranch area", "Southeast Gilbert"],
    localRoofingNotes: [
      "One of the fastest growing cities in the US — significant new construction activity",
      "HOA communities are ubiquitous with strict architectural guidelines",
      "Tile roofing is the dominant style in most subdivisions",
      "Family-oriented neighborhoods mean high homeowner awareness of maintenance",
      "Summer heat causes rapid thermal cycling damage to improperly installed roofs",
    ],
    featuredServices: ["tile-roofing", "new-roof-installation", "storm-damage-roofing", "roof-repair"],
    nearbyCity: ["chandler-az", "mesa-az", "queen-creek-az", "tempe-az"],
    description: "Gilbert consistently ranks among the safest and most desirable cities in the US — and its homeowners expect the same quality in their roofing contractors. XRP Roofing brings top-tier workmanship to Gilbert's growing neighborhoods and communities.",
  },
  {
    slug: "tempe-az",
    name: "Tempe",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Tempe Marketplace area", "McClintock area", "Arizona State University vicinity", "Kyrene area", "South Tempe", "Millbrae area", "Old Tempe"],
    localRoofingNotes: [
      "Dense urban environment with mix of commercial and residential roofing",
      "University-adjacent areas have older housing stock needing frequent repair",
      "Commercial flat roofing demand high along the I-10 and US-60 corridors",
      "Shingle and flat roofs common on older post-war homes",
      "High rental property concentration increases owner demand for durable, low-maintenance solutions",
    ],
    featuredServices: ["flat-roofing", "shingle-roofing", "roof-repair", "commercial-roofing"],
    nearbyCity: ["phoenix-az", "mesa-az", "chandler-az", "scottsdale-az"],
    description: "Tempe's unique blend of urban commercial zones, university neighborhoods, and established residential areas creates diverse roofing needs. XRP Roofing handles everything from single-family home repairs to large commercial flat roof projects.",
  },
  {
    slug: "glendale-az",
    name: "Glendale",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Glendale antique district", "Westgate area", "Arrowhead Ranch", "Thunderbird area", "Camelback Ranch area", "North Glendale", "Central Glendale"],
    localRoofingNotes: [
      "Mix of historic homes in central Glendale and newer communities in the north",
      "Arrowhead area features upscale tile roofing common in master-planned communities",
      "Sports and entertainment corridors have significant commercial roofing needs",
      "Older central Glendale homes often need full re-roof due to deferred maintenance",
      "Western exposure increases sun damage on sunset-facing roof slopes",
    ],
    featuredServices: ["tile-roofing", "shingle-roofing", "roof-replacement", "commercial-roofing"],
    nearbyCity: ["phoenix-az", "peoria-az", "surprise-az", "avondale-az"],
    description: "From the historic homes of central Glendale to the master-planned communities of Arrowhead Ranch, XRP Roofing has served Glendale homeowners and businesses with expert craftsmanship and honest pricing.",
  },
  {
    slug: "peoria-az",
    name: "Peoria",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Lake Pleasant area", "Vistancia", "Westwing Pointe", "Peoria Sports Complex area", "Old Town Peoria", "Pleasant Valley", "Crossing Trails area"],
    localRoofingNotes: [
      "Vistancia and other master-planned communities require HOA-approved materials",
      "Lake Pleasant proximity brings elevated humidity levels compared to central valley",
      "North Peoria's newer construction is predominantly tile roofing",
      "Monsoon storm paths frequently impact the northwest valley",
      "High desert elevation in northern areas means greater temperature swings",
    ],
    featuredServices: ["tile-roofing", "new-roof-installation", "storm-damage-roofing", "roof-replacement"],
    nearbyCity: ["glendale-az", "surprise-az", "phoenix-az", "anthem-az"],
    description: "Peoria's rapid northward growth has produced thousands of new homes that need quality roofing maintenance and repair. XRP Roofing understands the unique demands of Peoria's lake communities, master-planned subdivisions, and established neighborhoods.",
  },
  {
    slug: "surprise-az",
    name: "Surprise",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Surprise Farms", "Marley Park", "Corte Sierra", "Sun Village area", "Greer Ranch", "Bell Road corridor", "West Surprise"],
    localRoofingNotes: [
      "Large active adult communities create consistent re-roofing demand",
      "Extreme western sun exposure accelerates material deterioration",
      "New construction booming — demand for new roof installations high",
      "Tile and shingle both common depending on neighborhood age and HOA rules",
      "Dust storms (haboobs) from the west can cause significant debris damage",
    ],
    featuredServices: ["tile-roofing", "shingle-roofing", "new-roof-installation", "roof-repair"],
    nearbyCity: ["peoria-az", "glendale-az", "goodyear-az", "sun-city-az"],
    description: "Surprise is one of Arizona's fastest-growing cities, and its mix of active adult communities and young family neighborhoods creates steady demand for quality roofing. XRP Roofing provides reliable service throughout Surprise and the northwest valley.",
  },
  {
    slug: "goodyear-az",
    name: "Goodyear",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Palm Valley", "Estrella Mountain Ranch", "Pebblecreek area", "Cottonflower area", "Canyon Trails", "Sedella area", "West Goodyear"],
    localRoofingNotes: [
      "Estrella Mountain Ranch features strict HOA tile requirements",
      "West valley heat is among the most intense in the Phoenix metro",
      "Military and industrial corridors add commercial roofing demand",
      "Rapidly expanding residential growth means constant new installation needs",
      "Monsoon storm water management is critical on low-slope Goodyear rooftops",
    ],
    featuredServices: ["tile-roofing", "flat-roofing", "new-roof-installation", "commercial-roofing"],
    nearbyCity: ["avondale-az", "surprise-az", "buckeye-az", "litchfield-park-az"],
    description: "Goodyear's explosive growth and master-planned communities make it one of the most active roofing markets in the west valley. XRP Roofing serves Goodyear homeowners and businesses with the expertise and responsiveness they deserve.",
  },
  {
    slug: "buckeye-az",
    name: "Buckeye",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Verrado", "Tartesso", "Blue Horizons", "Festival Foothills", "Southern Buckeye", "Sundance area", "West Buckeye"],
    localRoofingNotes: [
      "One of the fastest growing cities in the US by percentage",
      "Verrado's historic-inspired architecture often requires specific tile styles",
      "Far west valley location means maximum UV exposure and extreme heat",
      "Many properties are new builds transitioning out of builder warranty",
      "Wind exposure on open desert lots accelerates edge flashing damage",
    ],
    featuredServices: ["tile-roofing", "new-roof-installation", "shingle-roofing", "storm-damage-roofing"],
    nearbyCity: ["goodyear-az", "avondale-az", "surprise-az", "litchfield-park-az"],
    description: "Buckeye is transforming from a small agricultural town into one of Arizona's premier planned communities. XRP Roofing supports this growth by providing new installations, warranty-out repairs, and expert roofing service for Buckeye's expanding neighborhoods.",
  },
  {
    slug: "avondale-az",
    name: "Avondale",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Garden Lakes", "Avondale Estates", "Palm Valley area", "Phoenix International Raceway vicinity", "Coldwater area", "West McDowell corridor", "Central Avondale"],
    localRoofingNotes: [
      "Mix of established neighborhoods and newer developments",
      "Flat and shingle roofs common on older Avondale homes",
      "Proximity to Loop 101 commercial corridors creates commercial roofing demand",
      "Heat retention in urban Avondale makes cool-roof coatings highly beneficial",
      "Seasonal flooding risk in low-lying areas requires proper roof drainage attention",
    ],
    featuredServices: ["shingle-roofing", "flat-roofing", "roof-repair", "roof-coatings"],
    nearbyCity: ["goodyear-az", "glendale-az", "phoenix-az", "litchfield-park-az"],
    description: "Avondale's working-class neighborhoods and growing commercial zones need dependable roofing at fair prices. XRP Roofing delivers honest assessments, quality repairs, and full re-roof services that Avondale homeowners can trust.",
  },
  {
    slug: "queen-creek-az",
    name: "Queen Creek",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Manville", "Hastings Farms", "Sossaman Estates", "Cortina area", "Barney Farms", "Encanterra", "East Queen Creek"],
    localRoofingNotes: [
      "Fast-growing semi-rural community with large lot homes",
      "Agricultural roots mean many properties have outbuildings needing commercial roofing",
      "Tile roofing dominates in the upscale planned communities",
      "Southeast valley monsoon paths deliver some of the heaviest storm activity",
      "Encanterra and other resort communities have strict HOA material requirements",
    ],
    featuredServices: ["tile-roofing", "storm-damage-roofing", "new-roof-installation", "commercial-roofing"],
    nearbyCity: ["gilbert-az", "chandler-az", "maricopa-az", "apache-junction-az"],
    description: "Queen Creek blends rural Arizona character with modern planned communities and upscale developments. XRP Roofing understands the unique combination of agricultural, residential, and commercial roofing needs that define this fast-growing community.",
  },
  {
    slug: "casa-grande-az",
    name: "Casa Grande",
    state: "AZ",
    county: "Pinal County",
    neighborhoods: ["North Casa Grande", "Historic Downtown area", "Francisco Grande area", "Desert Sky area", "Casa Grande Industrial Park vicinity", "East Cottonwood area", "Toltec area"],
    localRoofingNotes: [
      "Located at the midpoint between Phoenix and Tucson — extreme desert heat",
      "Significant industrial and logistics roofing demand near I-10 corridor",
      "Many older homes with original shingle or built-up roofs overdue for replacement",
      "Dust storms from surrounding farmland cause unique abrasion damage",
      "Residential growth accelerating as Phoenix commuters relocate for affordability",
    ],
    featuredServices: ["shingle-roofing", "flat-roofing", "commercial-roofing", "roof-replacement"],
    nearbyCity: ["maricopa-az", "coolidge-az", "apache-junction-az", "florence-az"],
    description: "Casa Grande sits at a strategic crossroads between Phoenix and Tucson, with growing residential neighborhoods and a thriving industrial sector. XRP Roofing brings Phoenix-level expertise to Casa Grande homeowners and commercial property owners.",
  },
  {
    slug: "maricopa-az",
    name: "Maricopa",
    state: "AZ",
    county: "Pinal County",
    neighborhoods: ["Smith Farms", "Glennwilde", "Rancho El Dorado", "Province", "Homestead area", "Cobblestone Farms", "South Maricopa"],
    localRoofingNotes: [
      "Relatively new city — most homes built post-2000 with tile roofing",
      "Remote location means limited local roofing competition — quality matters",
      "HOA requirements are common throughout most neighborhoods",
      "Pinal County desert environment has extreme heat and significant dust events",
      "Extended sun exposure on south-facing slopes accelerates underlayment degradation",
    ],
    featuredServices: ["tile-roofing", "roof-repair", "storm-damage-roofing", "roof-replacement"],
    nearbyCity: ["casa-grande-az", "chandler-az", "queen-creek-az", "florence-az"],
    description: "Maricopa is one of Arizona's youngest cities, yet its rapid residential growth has created immediate needs for experienced roofing contractors. XRP Roofing serves Maricopa's HOA communities with professional installations, repairs, and replacements.",
  },
  {
    slug: "apache-junction-az",
    name: "Apache Junction",
    state: "AZ",
    county: "Pinal County",
    neighborhoods: ["Gold Canyon area", "Apache Junction Heights", "Superstition Springs area", "Lost Dutchman area", "Broadway Road corridor", "East Apache Junction", "Desert Vista area"],
    localRoofingNotes: [
      "Rocky desert terrain and mountain proximity mean significant wind events",
      "Many manufactured and modular homes require specialized roofing approaches",
      "Superstition Mountain area properties face unique debris and weather challenges",
      "Retirement community concentration creates re-roofing demand on aging homes",
      "Shingle and metal roofing popular on properties with rural character",
    ],
    featuredServices: ["shingle-roofing", "metal-roofing", "roof-repair", "storm-damage-roofing"],
    nearbyCity: ["mesa-az", "queen-creek-az", "gold-canyon-area", "casa-grande-az"],
    description: "Apache Junction's rugged desert setting near the Superstition Mountains creates unique roofing challenges. XRP Roofing provides durable solutions built to withstand the wind, dust, and extreme heat that define this unique East Valley community.",
  },
  {
    slug: "fountain-hills-az",
    name: "Fountain Hills",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Fountain Hills", "Firerock area", "Eagle Mountain area", "Fountain Hills Boulevard corridor", "North Heights", "Panorama Drive area", "East Fountain Hills"],
    localRoofingNotes: [
      "Upscale hillside properties require experienced crews for steep-slope work",
      "High elevation means greater temperature swings than valley floor",
      "HOA requirements and architectural committees are very active",
      "Tile roofing predominates with clay tile popular on luxury homes",
      "Wind exposure on elevated terrain accelerates edge and ridge damage",
    ],
    featuredServices: ["tile-roofing", "roof-repair", "new-roof-installation", "storm-damage-roofing"],
    nearbyCity: ["scottsdale-az", "mesa-az", "paradise-valley-az", "apache-junction-az"],
    description: "Fountain Hills is known for its iconic fountain, stunning mountain views, and upscale desert lifestyle. XRP Roofing brings the precision and craftsmanship that Fountain Hills homeowners expect, working seamlessly with HOAs and architectural committees.",
  },
  {
    slug: "paradise-valley-az",
    name: "Paradise Valley",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Camelback Mountain area", "Mummy Mountain area", "Lincoln Drive corridor", "Invergordon area", "McDonald Drive corridor", "Clearwater Hills", "Central Paradise Valley"],
    localRoofingNotes: [
      "One of the wealthiest municipalities in the US — only premium materials acceptable",
      "Large estate homes require specialized high-end tile and slate roofing expertise",
      "Strict municipal design standards govern visible roofing materials and colors",
      "Hillside construction means complex flashing and drainage requirements",
      "HOA and town council architectural reviews are mandatory for exterior changes",
    ],
    featuredServices: ["tile-roofing", "new-roof-installation", "roof-replacement", "metal-roofing"],
    nearbyCity: ["scottsdale-az", "phoenix-az", "fountain-hills-az", "tempe-az"],
    description: "Paradise Valley's world-class residential estates demand roofing contractors who understand luxury construction standards. XRP Roofing has the experience, materials knowledge, and professionalism to serve Paradise Valley's most discerning homeowners.",
  },
  {
    slug: "sun-city-az",
    name: "Sun City",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Sun City Center area", "Bell Road corridor", "103rd Avenue area", "Grand Avenue area", "Sun City Commons area", "Cameo Drive area", "East Sun City"],
    localRoofingNotes: [
      "Original Sun City homes are 50+ years old with significant re-roofing demand",
      "Active adult community — homeowners want reliable, hassle-free contractors",
      "Flat and low-slope roofs common on mid-century ranch-style homes",
      "Del Webb original construction often used materials now past useful life",
      "Community management committees govern exterior appearance standards",
    ],
    featuredServices: ["flat-roofing", "shingle-roofing", "roof-replacement", "roof-coatings"],
    nearbyCity: ["surprise-az", "peoria-az", "sun-city-west-az", "glendale-az"],
    description: "Sun City was America's first major retirement community, and its aging housing stock creates significant re-roofing demand. XRP Roofing specializes in the efficient, respectful service that Sun City's active adult residents appreciate.",
  },
  {
    slug: "sun-city-west-az",
    name: "Sun City West",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["RH Johnson Boulevard area", "Stardust area", "Desert Oasis area", "Sun City West Center area", "Corte Bella area", "North Sun City West", "West Camino area"],
    localRoofingNotes: [
      "Homes from the 1980s–1990s with original tile or shingle reaching end of life",
      "Active adult community values prompt communication and clean worksites",
      "Tile roofing common — many need re-felt or full replacement due to underlayment age",
      "HOA community standards require color and style matching",
      "Mild slope roofs common — drainage and flashing inspection important",
    ],
    featuredServices: ["tile-roofing", "roof-replacement", "shingle-roofing", "roof-repair"],
    nearbyCity: ["sun-city-az", "surprise-az", "peoria-az", "glendale-az"],
    description: "Sun City West offers the same active adult lifestyle as its neighbor with homes predominantly from the 1980s and 1990s. XRP Roofing provides timely, professional roofing services tailored to the needs of Sun City West's retirement community.",
  },
  {
    slug: "litchfield-park-az",
    name: "Litchfield Park",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Old Litchfield Park historic area", "Wigwam area", "Dreaming Summit", "Country Club area", "Litchfield Green area", "Palm Valley adjacent", "East Litchfield Park"],
    localRoofingNotes: [
      "Historic town with character homes requiring careful material matching",
      "Prestigious Wigwam resort area sets high appearance standards for surrounding homes",
      "Upscale residential community with active HOA oversight",
      "Tile roofing dominates in the master-planned sections",
      "Large mature trees mean debris accumulation requiring regular maintenance",
    ],
    featuredServices: ["tile-roofing", "roof-repair", "new-roof-installation", "storm-damage-roofing"],
    nearbyCity: ["goodyear-az", "avondale-az", "buckeye-az", "surprise-az"],
    description: "Litchfield Park is one of the West Valley's most charming and well-kept communities. XRP Roofing honors the character of Litchfield Park's historic homes while delivering modern performance and reliability.",
  },
  {
    slug: "tolleson-az",
    name: "Tolleson",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Tolleson Union High School area", "West Tolleson", "Industrial Park vicinity", "Central Tolleson", "Southern Avenue corridor", "99th Avenue area", "Van Buren corridor"],
    localRoofingNotes: [
      "Industrial and logistics hub with high demand for commercial flat roofing",
      "Many working-class residential neighborhoods with older housing stock",
      "Industrial pollutants can accelerate roofing material degradation",
      "Flat commercial roofs predominant along I-10 industrial corridor",
      "Shingle and flat residential roofs common in established neighborhoods",
    ],
    featuredServices: ["flat-roofing", "commercial-roofing", "shingle-roofing", "roof-coatings"],
    nearbyCity: ["avondale-az", "phoenix-az", "goodyear-az", "glendale-az"],
    description: "Tolleson's industrial strength and residential neighborhoods both depend on quality roofing. XRP Roofing provides commercial flat roofing solutions for Tolleson's warehouses and distribution centers, as well as residential services for local homeowners.",
  },
  {
    slug: "el-mirage-az",
    name: "El Mirage",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["El Mirage Road corridor", "Dysart Road area", "West El Mirage", "Central El Mirage", "Palmaire area", "Thunderbird Road corridor", "North El Mirage"],
    localRoofingNotes: [
      "Affordable housing community with high demand for cost-effective solutions",
      "Older housing stock from the 1970s–1990s with deferred roofing maintenance",
      "Shingle and flat roofs predominate over tile",
      "Open desert exposure on west and north sides increases wind damage risk",
      "Budget-conscious homeowners benefit from roof coating solutions over full replacement",
    ],
    featuredServices: ["shingle-roofing", "roof-repair", "roof-coatings", "roof-replacement"],
    nearbyCity: ["surprise-az", "peoria-az", "glendale-az", "sun-city-az"],
    description: "El Mirage homeowners deserve quality roofing at honest prices. XRP Roofing provides transparent estimates, durable materials, and dependable workmanship to keep El Mirage homes protected from Arizona's demanding climate.",
  },
  {
    slug: "cave-creek-az",
    name: "Cave Creek",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Cave Creek", "Tatum Ranch area", "Desert Hills area", "Spur Cross area", "Black Mountain area", "New River Road corridor", "North Cave Creek"],
    localRoofingNotes: [
      "Rustic desert town with unique architectural character — natural materials preferred",
      "High desert elevation means extreme UV and wider temperature swings",
      "Many custom homes and ranch properties with unique roofing needs",
      "Metal and tile roofing popular to complement the desert aesthetic",
      "Wildfire risk in surrounding desert requires fire-rated roofing materials",
    ],
    featuredServices: ["metal-roofing", "tile-roofing", "roof-repair", "new-roof-installation"],
    nearbyCity: ["carefree-az", "scottsdale-az", "anthem-az", "phoenix-az"],
    description: "Cave Creek's unique cowboy-meets-luxury character calls for roofing contractors who respect both aesthetics and performance. XRP Roofing works with Cave Creek's custom homes, ranches, and desert estates to deliver roofing that fits the landscape.",
  },
  {
    slug: "carefree-az",
    name: "Carefree",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Downtown Carefree", "Boulders area", "Carefree Highway corridor", "Black Mountain area", "Tranquil Trail area", "Sundial area", "North Carefree"],
    localRoofingNotes: [
      "Small luxury resort town with high-end custom home roofing needs",
      "The Boulders community requires premium tile matching existing architecture",
      "Elevated location increases wind and storm exposure",
      "Desert landscaping creates specific debris and drainage considerations",
      "Strict town design standards govern material choices and aesthetics",
    ],
    featuredServices: ["tile-roofing", "new-roof-installation", "roof-replacement", "metal-roofing"],
    nearbyCity: ["cave-creek-az", "scottsdale-az", "fountain-hills-az", "anthem-az"],
    description: "Carefree lives up to its name — but its luxury homes and resort properties need serious roofing expertise. XRP Roofing brings premium craftsmanship and meticulous attention to detail to every project in this prestigious community.",
  },
  {
    slug: "anthem-az",
    name: "Anthem",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Anthem Country Club", "Anthem Parkside", "Anthem Merrill Ranch", "Daisy Mountain area", "New River adjacent", "Gavilan Peak area", "West Anthem"],
    localRoofingNotes: [
      "Master-planned Del Webb community with active HOA and strict material requirements",
      "North Valley location at higher elevation with greater storm frequency",
      "Anthem Country Club area features upscale tile roofing throughout",
      "Homes from early 2000s are approaching common re-roof timelines",
      "Wind exposure from I-17 corridor and open desert is significant",
    ],
    featuredServices: ["tile-roofing", "roof-replacement", "storm-damage-roofing", "roof-repair"],
    nearbyCity: ["cave-creek-az", "peoria-az", "phoenix-az", "carefree-az"],
    description: "Anthem is one of Arizona's premier master-planned communities. XRP Roofing understands the HOA requirements, quality standards, and architectural guidelines that govern Anthem homes — ensuring compliant, beautiful, long-lasting results.",
  },
  {
    slug: "florence-az",
    name: "Florence",
    state: "AZ",
    county: "Pinal County",
    neighborhoods: ["Historic Downtown Florence", "Cactus Forest area", "Hunt Highway corridor", "Magma area", "Central Florence", "South Florence", "West Florence industrial area"],
    localRoofingNotes: [
      "Rural Pinal County location with intense desert heat and UV exposure",
      "Mix of historic adobe-style homes and newer tract construction",
      "Limited local roofing options — residents rely on Phoenix metro contractors",
      "Extreme heat demands reflective or cool-roof materials for energy savings",
      "Older homes frequently have original built-up or gravel roofing needing replacement",
    ],
    featuredServices: ["shingle-roofing", "flat-roofing", "roof-replacement", "roof-coatings"],
    nearbyCity: ["casa-grande-az", "coolidge-az", "maricopa-az", "apache-junction-az"],
    description: "Florence's historic character and growing residential base deserve professional roofing solutions. XRP Roofing extends its Phoenix-quality service to Florence, providing honest assessments and durable work that stands up to Pinal County's demanding climate.",
  },
  {
    slug: "coolidge-az",
    name: "Coolidge",
    state: "AZ",
    county: "Pinal County",
    neighborhoods: ["Downtown Coolidge", "Arizona Dry Heat area", "Coolidge Airport area", "North Coolidge", "Central McCartney Road area", "East Coolidge", "South Coolidge industrial"],
    localRoofingNotes: [
      "Agricultural community with significant farm building and outbuilding roofing needs",
      "Extreme desert heat in Pinal County — one of the hottest areas in the US",
      "Many older homes with original shingle or gravel roofs overdue for replacement",
      "Metal roofing popular for agricultural structures and outbuildings",
      "Cottonwood and other farm tree debris creates maintenance demands",
    ],
    featuredServices: ["metal-roofing", "shingle-roofing", "flat-roofing", "roof-replacement"],
    nearbyCity: ["casa-grande-az", "florence-az", "maricopa-az", "chandler-az"],
    description: "Coolidge is a hardworking agricultural community in the heart of Pinal County. XRP Roofing serves Coolidge's farms, homes, and businesses with dependable roofing that stands up to some of Arizona's most extreme desert conditions.",
  },
  {
    slug: "wickenburg-az",
    name: "Wickenburg",
    state: "AZ",
    county: "Maricopa County",
    neighborhoods: ["Historic Downtown Wickenburg", "Rancho de los Caballeros area", "Vulture Mine Road area", "Constellation area", "Wickenburg Airport area", "Jack Burden Road corridor", "North Wickenburg"],
    localRoofingNotes: [
      "Historic desert town with mix of ranch-style and adobe architecture",
      "Dude ranch and resort properties have unique commercial roofing needs",
      "High desert location with broader temperature range than valley floor",
      "Metal roofing popular for ranches and outbuildings",
      "Remote location requires contractors willing to travel — XRP Roofing serves the area",
    ],
    featuredServices: ["metal-roofing", "shingle-roofing", "roof-repair", "flat-roofing"],
    nearbyCity: ["surprise-az", "peoria-az", "phoenix-az", "anthem-az"],
    description: "Wickenburg's authentic western character and resort properties need roofing contractors who can match the town's rugged aesthetic with professional quality. XRP Roofing serves Wickenburg's unique mix of residential, ranch, and hospitality properties.",
  },
  {
    slug: "payson-az",
    name: "Payson",
    state: "AZ",
    county: "Gila County",
    neighborhoods: ["Downtown Payson", "Star Valley area", "Rim Road area", "McLane Creek area", "Payson Ranchettes", "Airport Road area", "East Payson"],
    localRoofingNotes: [
      "Mountain community at 4,900 ft elevation with true four-season weather",
      "Snow load is a real factor — roofing must be engineered for snow weight",
      "Monsoon season brings heavy rain and frequent lightning in the Rim Country",
      "Pine needles from ponderosa pines create significant debris accumulation",
      "Metal roofing popular for snow shedding and fire resistance in pine forest setting",
    ],
    featuredServices: ["metal-roofing", "shingle-roofing", "storm-damage-roofing", "roof-repair"],
    nearbyCity: ["fountain-hills-az", "apache-junction-az", "mesa-az", "scottsdale-az"],
    description: "Payson's mountain setting brings roofing challenges unlike anywhere else in Arizona. At nearly 5,000 feet, Payson homes face snow loads, intense monsoon rains, pine needle buildup, and freeze-thaw cycles. XRP Roofing understands these unique demands.",
  },
];

export const cityMap = Object.fromEntries(cities.map((c) => [c.slug, c]));

export function getCity(slug: string): City | undefined {
  return cityMap[slug];
}

export function getNearbyCities(slug: string): City[] {
  const city = getCity(slug);
  if (!city) return [];
  return city.nearbyCity
    .map((s) => getCity(s))
    .filter(Boolean) as City[];
}
